#!/usr/bin/env bash
# KTrace Connector — One-line install
# Usage (generated by KTrace frontend):
#   curl -sL https://kiteclaw.xyz/connector/install.sh | \
#     CONNECTOR_TOKEN=ktrace_cc_... AA_WALLET=0x... SESSION_ID=0x... \
#     OWNER_EOA=0x... SESSION_KEY=0x... bash
set -euo pipefail

BACKEND_URL="${BACKEND_URL:-https://kiteclaw.xyz}"
AA_WALLET="${AA_WALLET:-}"
SESSION_ID="${SESSION_ID:-}"
OWNER_EOA="${OWNER_EOA:-}"
SESSION_KEY="${SESSION_KEY:-}"

# ── Validate ──────────────────────────────────────────────────────────────────
fail() { echo "✗ $1" >&2; exit 1; }

[[ -z "$AA_WALLET" ]]       && fail "AA_WALLET is required"
[[ -z "$SESSION_ID" ]]      && fail "SESSION_ID is required"
[[ -z "$OWNER_EOA" ]]       && fail "OWNER_EOA is required"
[[ -z "$SESSION_KEY" ]]     && fail "SESSION_KEY is required"

command -v node >/dev/null 2>&1 || fail "Node.js ≥18 is required. Install from https://nodejs.org"
NODE_MAJOR=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
[[ "$NODE_MAJOR" -lt 18 ]] && fail "Node.js ≥18 required (found v$(node --version))"

# ── Install dir ───────────────────────────────────────────────────────────────
INSTALL_DIR="$HOME/.ktrace-connector"
mkdir -p "$INSTALL_DIR"
chmod 700 "$INSTALL_DIR"

echo "→ Downloading proxy..."
curl -sL "${BACKEND_URL}/connector/local-signing-proxy.js" \
  -o "$INSTALL_DIR/local-signing-proxy.js" \
  || fail "Failed to download proxy from ${BACKEND_URL}"

echo "→ Installing dependencies..."
cat > "$INSTALL_DIR/package.json" <<'PKGJSON'
{
  "name": "ktrace-connector",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "ethers": "^6.0.0"
  }
}
PKGJSON
(cd "$INSTALL_DIR" && npm install --silent --no-fund --no-audit 2>/dev/null)

# ── Write config ──────────────────────────────────────────────────────────────
echo "→ Writing config..."
cat > "$INSTALL_DIR/config.json" <<CONFIG
{
  "backendUrl": "${BACKEND_URL}",
  "aaWallet": "${AA_WALLET}",
  "sessionId": "${SESSION_ID}",
  "ownerEoa": "${OWNER_EOA}",
  "sessionPrivateKey": "${SESSION_KEY}"
}
CONFIG
chmod 600 "$INSTALL_DIR/config.json"

# ── Patch Claude Code MCP config ──────────────────────────────────────────────
patch_claude_json() {
  local cfg="$1"
  if [[ ! -f "$cfg" ]]; then
    mkdir -p "$(dirname "$cfg")"
    echo '{"mcpServers":{}}' > "$cfg"
  fi
  node - "$cfg" "$INSTALL_DIR/local-signing-proxy.js" <<'NODEEOF'
const fs = require('fs');
const [,, cfgPath, proxyPath] = process.argv;
let json = {};
try { json = JSON.parse(fs.readFileSync(cfgPath, 'utf8')); } catch {}
json.mcpServers = json.mcpServers || {};
json.mcpServers['ktrace-proxy'] = { command: 'node', args: [proxyPath] };
fs.writeFileSync(cfgPath, JSON.stringify(json, null, 2));
NODEEOF
}

# Try all known Claude Code config locations
PATCHED=0
for cfg in \
  "$HOME/.claude/claude.json" \
  "$HOME/Library/Application Support/Claude/claude.json" \
  "$APPDATA/Claude/claude.json" \
  "$HOME/.config/claude/claude.json"
do
  if [[ -f "$cfg" ]] || [[ "$cfg" == "$HOME/.claude/claude.json" ]]; then
    patch_claude_json "$cfg" && PATCHED=1 && break
  fi
done

# ── Clear history entry ───────────────────────────────────────────────────────
history -d "$(history 1 | awk '{print $1}')" 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✓ KTrace connector installed"
echo "  Config: $INSTALL_DIR/config.json"
if [[ "$PATCHED" == "1" ]]; then
  echo "  MCP:    auto-added to Claude Code config"
else
  echo ""
  echo "  Add to Claude Code manually (~/.claude/claude.json):"
  echo "  {\"mcpServers\":{\"ktrace-proxy\":{\"command\":\"node\",\"args\":[\"$INSTALL_DIR/local-signing-proxy.js\"]}}}"
fi
echo ""
echo "  Restart Claude Code to activate."
echo ""
echo "  To clear this command from shell history: history -c"
