#!/usr/bin/env bash
# KTrace Connector — One-line install
# Usage (generated by KTrace frontend):
#   curl -sL https://kiteclaw.duckdns.org/connector/install.sh | \
#     BACKEND_URL=https://kiteclaw.duckdns.org AA_WALLET=0x... SESSION_ID=0x... \
#     OWNER_EOA=0x... SESSION_KEY=0x... bash
set -euo pipefail

BACKEND_URL="${BACKEND_URL:-https://kiteclaw.duckdns.org}"
AA_WALLET="${AA_WALLET:-}"
SESSION_ID="${SESSION_ID:-}"
OWNER_EOA="${OWNER_EOA:-}"
SESSION_KEY="${SESSION_KEY:-}"

# ── Validate ──────────────────────────────────────────────────────────────────
fail() { echo "✗ $1" >&2; exit 1; }

[[ -z "$AA_WALLET" ]]       && fail "AA_WALLET is required"
[[ -z "$SESSION_ID" ]]      && fail "SESSION_ID is required"
[[ -z "$OWNER_EOA" ]]       && fail "OWNER_EOA is required"
[[ -z "$SESSION_KEY" ]]     && fail "SESSION_KEY is required"

command -v node >/dev/null 2>&1 || fail "Node.js >=18 is required. Install from https://nodejs.org"
NODE_MAJOR=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
[[ "$NODE_MAJOR" -lt 18 ]] && fail "Node.js >=18 required (found v$(node --version))"

# ── Install dir ───────────────────────────────────────────────────────────────
INSTALL_DIR="$HOME/.ktrace-connector"
mkdir -p "$INSTALL_DIR"
chmod 700 "$INSTALL_DIR"

echo "> Downloading proxy..."
curl -sL "${BACKEND_URL}/connector/local-signing-proxy.js" \
  -o "$INSTALL_DIR/local-signing-proxy.js" \
  || fail "Failed to download proxy from ${BACKEND_URL}"

echo "> Installing dependencies..."
cat > "$INSTALL_DIR/package.json" <<'PKGJSON'
{
  "name": "ktrace-connector",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "ethers": "^6.0.0"
  }
}
PKGJSON
(cd "$INSTALL_DIR" && npm install --silent --no-fund --no-audit 2>/dev/null)

# ── Write config ──────────────────────────────────────────────────────────────
echo "> Writing config..."
cat > "$INSTALL_DIR/config.json" <<CONFIG
{
  "backendUrl": "${BACKEND_URL}",
  "aaWallet": "${AA_WALLET}",
  "sessionId": "${SESSION_ID}",
  "ownerEoa": "${OWNER_EOA}",
  "sessionPrivateKey": "${SESSION_KEY}"
}
CONFIG
chmod 600 "$INSTALL_DIR/config.json"

# ── Add MCP server to Claude Code ────────────────────────────────────────────
PROXY_PATH="$INSTALL_DIR/local-signing-proxy.js"

echo "> Adding MCP server to Claude Code..."
if command -v claude >/dev/null 2>&1; then
  claude mcp remove ktrace-proxy -s user 2>/dev/null || true
  claude mcp add ktrace-proxy -s user -- node "$PROXY_PATH"
  echo "  MCP server added via 'claude mcp add'"
else
  echo "  'claude' CLI not found — add MCP manually:"
  echo "    claude mcp add ktrace-proxy -s user -- node \"$PROXY_PATH\""
fi

# ── Clear history entry ───────────────────────────────────────────────────────
history -d "$(history 1 | awk '{print $1}')" 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "Done! KTrace connector installed"
echo "  Config: $INSTALL_DIR/config.json"
echo ""
echo "  Restart Claude Code to activate."
echo ""
echo "  To clear this command from shell history: history -c"
