# KTrace Connector — One-line install (PowerShell)
# Usage (generated by KTrace frontend):
#   $env:BACKEND_URL="https://..."; $env:AA_WALLET="0x..."; $env:SESSION_ID="0x..."; $env:OWNER_EOA="0x..."; $env:SESSION_KEY="0x..."; irm https://kiteclaw.duckdns.org/connector/install.ps1 | iex
$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$BACKEND_URL = if ($env:BACKEND_URL) { $env:BACKEND_URL } else { "https://kiteclaw.duckdns.org" }
$AA_WALLET   = $env:AA_WALLET
$SESSION_ID  = $env:SESSION_ID
$OWNER_EOA   = $env:OWNER_EOA
$SESSION_KEY  = $env:SESSION_KEY

function Fail($msg) { Write-Error $msg; exit 1 }

if (-not $AA_WALLET)  { Fail "AA_WALLET is required" }
if (-not $SESSION_ID) { Fail "SESSION_ID is required" }
if (-not $OWNER_EOA)  { Fail "OWNER_EOA is required" }
if (-not $SESSION_KEY) { Fail "SESSION_KEY is required" }

$nodeVersion = & node -e "process.stdout.write(process.versions.node.split('.')[0])" 2>$null
if (-not $nodeVersion -or [int]$nodeVersion -lt 18) { Fail "Node.js >= 18 required. Install from https://nodejs.org" }

# Install dir
$INSTALL_DIR = Join-Path $HOME ".ktrace-connector"
if (-not (Test-Path $INSTALL_DIR)) { New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null }

Write-Host "> Downloading proxy + SDK..."
Invoke-WebRequest -Uri "$BACKEND_URL/connector/local-signing-proxy.js" -OutFile (Join-Path $INSTALL_DIR "local-signing-proxy.js") -UseBasicParsing

$LIB_DIR = Join-Path $INSTALL_DIR "lib"
if (-not (Test-Path $LIB_DIR)) { New-Item -ItemType Directory -Path $LIB_DIR -Force | Out-Null }
foreach ($f in @("gokite-aa-sdk.js", "aaConfig.js", "kiteRpc.js", "envProxy.js")) {
    Invoke-WebRequest -Uri "$BACKEND_URL/connector/lib/$f" -OutFile (Join-Path $LIB_DIR $f) -UseBasicParsing
}

Write-Host "> Installing dependencies..."
@"
{
  "name": "ktrace-connector",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "ethers": "^6.0.0",
    "undici": "^6.0.0"
  }
}
"@ | Set-Content (Join-Path $INSTALL_DIR "package.json") -Encoding UTF8

Push-Location $INSTALL_DIR
& npm install --silent --no-fund --no-audit 2>$null
Pop-Location

Write-Host "> Writing config..."
$config = @{
    backendUrl       = $BACKEND_URL
    aaWallet         = $AA_WALLET
    sessionId        = $SESSION_ID
    ownerEoa         = $OWNER_EOA
    sessionPrivateKey = $SESSION_KEY
} | ConvertTo-Json
Set-Content (Join-Path $INSTALL_DIR "config.json") $config -Encoding UTF8

# Add MCP server to Claude Code via CLI
$proxyPath = (Join-Path $INSTALL_DIR "local-signing-proxy.js") -replace '\\', '/'

Write-Host "> Adding MCP server to Claude Code..."
# Find claude binary — check common locations
$claudePath = $null
$candidates = @(
    (Join-Path $HOME ".local\bin\claude.exe"),
    (Join-Path $env:APPDATA "npm\claude.cmd"),
    (Join-Path $env:LOCALAPPDATA "Programs\claude\claude.exe")
)
foreach ($c in $candidates) { if (Test-Path $c) { $claudePath = $c; break } }
# Fallback: search PATH
if (-not $claudePath) {
    $found = Get-Command claude.exe -ErrorAction SilentlyContinue
    if ($found) { $claudePath = $found.Source }
}

if ($claudePath) {
    try { & $claudePath mcp remove ktrace-proxy -s user 2>$null } catch {}
    $ErrorActionPreference = "Stop"
    & $claudePath mcp add ktrace-proxy -s user -- node $proxyPath
    Write-Host "  MCP server added via 'claude mcp add'" -ForegroundColor Green
} else {
    Write-Host "  'claude' CLI not found — add MCP manually:" -ForegroundColor Yellow
    Write-Host "    claude mcp add ktrace-proxy -s user -- node `"$proxyPath`""
}

# Clear env vars with session key
Remove-Item Env:SESSION_KEY -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Done! KTrace connector installed" -ForegroundColor Green
Write-Host "  Config: $INSTALL_DIR\config.json"
Write-Host ""
Write-Host "  Restart Claude Code to activate." -ForegroundColor Cyan
Write-Host ""
Write-Host "  To clear PowerShell history: Clear-History" -ForegroundColor Yellow
